description: Attributes of the features or fields of a coverage range. Defined by a subset of the JSON Schema for the properties of a feature
type: object
required:
- type
- properties
properties:
   type:
     type: string
     enum:
     - object
   required:
     type: array
     minItems: 1
     items:
        type: string
   properties:
     type: object
     default: {}
     additionalProperties:
       type: object
       properties:
         title:
           type: string
         description:
           type: string
         type:
           type: string
           enum:
           - array
           - boolean
           - integer
           - 'null'
           - number
           - object
           - string
         enum:
           type: array
           minItems: 1
           items: {}
           uniqueItems: true
         format:
           type: string
         contentMediaType:
           type: string
         maximum:
           type: number
         exclusiveMaximum:
           type: number
         minimum:
           type: number
         exclusiveMinimum:
           type: number
         pattern:
           type: string
           format: regex
         maxItems:
           type: integer
           minimum: 0
         minItems:
           type: integer
           default: 0
           minimum: 0
         x-ogc-definition:
           type: string
           format: uri
         x-ogc-unit:
           type: string
         x-ogc-unitLang:
           type: string
