name: values-offset
in: query
description: |
   Specify the offset for a zone data output format such as PNG not supporting floating-point, to be applied after multiplying by the scale factor and resulting in the encoded integer values (e.g., 8-bit or 16-bit unsigned for PNG).
style: form
explode: false
required: false
schema:
  type: number
